name: sobre.
description: Editorial Technical Blog - Explorando tecnologia, cultura e economia
baseurl: "/sobre" # Isso diz ao Jekyll que seu site vive nessa subpasta
theme: minima
permalink: /:categories/:year/:month/:day/:title/
